name: "Docker"

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  check_changes:
    name: Check files
    outputs:
      docker_changes: ${{ steps.changes_docker.outputs.src }}
      gke_cluster_changes: ${{ steps.changes_terraform_gke_cluster.outputs.src }}
      helm_release_changes: ${{ steps.changes_terraform_helm_release.outputs.src }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes_docker
        with:
          filters: |
            src:
              - '*.go'
              - 'go.mod'
              - 'Dockerfile'

  docker:
    needs: check_changes
    if: needs.check_changes.outputs.docker_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codeexecute:${{ steps.semvers.outputs.version }}
