name: "Docker"

on:
  push:
    tags:
    - 'v*.*.*'
  pull_request:
    types: [opened, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: github.event_name != "pull_request"
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codeexecute:${{ env.RELEASE_VERSION }}
